package com.rk.terminal.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF102F60)
val md_theme_dark_primaryContainer = Color(0xFF2B4678)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFBFC6DC)
val md_theme_dark_onSecondary = Color(0xFF293041)
val md_theme_dark_secondaryContainer = Color(0xFF3F4759)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBE2F9)
val md_theme_dark_tertiary = Color(0xFFDEBCDF)
val md_theme_dark_onTertiary = Color(0xFF402843)
val md_theme_dark_tertiaryContainer = Color(0xFF583E5B)
val md_theme_dark_onTertiaryContainer = Color(0xFFFBD7FC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E9)
val md_theme_dark_surface = Color(0xFF111318)
val md_theme_dark_onSurface = Color(0xFFE2E2E9)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF2F3036)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E9)
val md_theme_dark_inversePrimary = Color(0xFF445E91)
val md_theme_dark_surfaceTint = Color(0xFFD8E2FF)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_scrim = Color(0xFF000000)
